services:
  api:
    image: app:latest
    container_name: api
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
          - 80:80
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
          - api